service: x-ray-demo
provider:
  name: aws
  runtime: nodejs8.10
  timeout: 28
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
functions:
  demo:
    handler: handler.demo
    events:
      - http:
          path: demo
          method: get